function(generate_postgres_errcodes INPUT_FILE OUTPUT_FILE)
  if(NOT EXISTS "${INPUT_FILE}")
    message(FATAL_ERROR "Input file ${INPUT_FILE} does not exist!")
  endif()

  message(STATUS "Generating errcodes.h from errcodes.txt using native CMake parser...")

  # Read the input file line by line
  file(STRINGS "${INPUT_FILE}" LINES)

  # Initialize the header content
  set(HEADER_CONTENT "/* autogenerated from src/backend/utils/errcodes.txt by CMake, do not edit */\n")
  string(APPEND HEADER_CONTENT "/* there is deliberately not an #ifndef ERRCODES_H here */\n\n")

  foreach(LINE ${LINES})
    # Replace all literal tab characters with standard spaces to avoid regex failures
    string(REPLACE "\t" " " LINE "${LINE}")
    string(REPLACE "\r" "" LINE "${LINE}")
    string(STRIP "${LINE}" LINE)

    # Skip comments and empty lines
    if(LINE MATCHES "^#" OR LINE STREQUAL "")
      continue()
    endif()

    # Handle Section headers
    if(LINE MATCHES "^Section:(.*)")
      set(SECTION_NAME "${CMAKE_MATCH_1}")
      string(STRIP "${SECTION_NAME}" SECTION_NAME)
      string(APPEND HEADER_CONTENT "\n/* ${SECTION_NAME} */\n")
      continue()
    endif()

    # Convert the space-separated line into a clean CMake list
    string(REPLACE " " ";" TOKENS "${LINE}")

    set(CLEAN_TOKENS "")
    foreach(TOKEN ${TOKENS})
      if(NOT TOKEN STREQUAL "")
        list(APPEND CLEAN_TOKENS "${TOKEN}")
      endif()
    endforeach()

    # Extract columns based on list indices
    list(LENGTH CLEAN_TOKENS TOKEN_COUNT)
    if(TOKEN_COUNT GREATER_EQUAL 3)
      list(GET CLEAN_TOKENS 0 SQL_STATE)
      list(GET CLEAN_TOKENS 2 MACRO_NAME)

      # Validate that the first token is a 5-character error code
      string(LENGTH "${SQL_STATE}" STATE_LEN)
      if(STATE_LEN EQUAL 5)
        string(SUBSTRING "${SQL_STATE}" 0 1 C1)
        string(SUBSTRING "${SQL_STATE}" 1 1 C2)
        string(SUBSTRING "${SQL_STATE}" 2 1 C3)
        string(SUBSTRING "${SQL_STATE}" 3 1 C4)
        string(SUBSTRING "${SQL_STATE}" 4 1 C5)

        set(FORMATTED_STATE "'${C1}','${C2}','${C3}','${C4}','${C5}'")
        string(APPEND HEADER_CONTENT "#define ${MACRO_NAME} MAKE_SQLSTATE(${FORMATTED_STATE})\n")
      endif()
    endif()
  endforeach()

  # Write the completed file to the destination
  file(WRITE "${OUTPUT_FILE}" "${HEADER_CONTENT}")
endfunction()
